-- Sprout MVP Schema

-- Enable UUID generation
create extension if not exists "uuid-ossp";

-- Talent profiles (fractional executives)
create table talent_profiles (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  title text not null,
  functions text[] not null default '{}',
  industries text[] not null default '{}',
  rate_min integer,
  rate_max integer,
  hours_per_week integer,
  bio text,
  linkedin_url text,
  created_at timestamptz not null default now()
);

-- Company profiles
create table company_profiles (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  company_name text not null,
  stage text,
  function_needed text not null,
  budget_monthly integer,
  hours_per_week integer,
  description text,
  created_at timestamptz not null default now()
);

-- Matches generated by Scout AI
create table matches (
  id uuid primary key default uuid_generate_v4(),
  talent_id uuid not null references talent_profiles(id) on delete cascade,
  company_id uuid not null references company_profiles(id) on delete cascade,
  score integer not null check (score >= 0 and score <= 100),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'expired')),
  scout_reasoning text,
  created_at timestamptz not null default now()
);

-- Introductions between matched talent and companies
create table introductions (
  id uuid primary key default uuid_generate_v4(),
  match_id uuid not null references matches(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'sent', 'accepted', 'declined', 'completed')),
  intro_sent_at timestamptz,
  meeting_booked_at timestamptz,
  outcome text,
  created_at timestamptz not null default now()
);

-- Row Level Security
alter table talent_profiles enable row level security;
alter table company_profiles enable row level security;
alter table matches enable row level security;
alter table introductions enable row level security;

-- Policies: users can read/write their own profiles
create policy "Users can manage their own talent profile"
  on talent_profiles for all
  using (auth.uid() = user_id);

create policy "Users can manage their own company profile"
  on company_profiles for all
  using (auth.uid() = user_id);

-- Matches are readable by both parties
create policy "Users can view their matches"
  on matches for select
  using (
    talent_id in (select id from talent_profiles where user_id = auth.uid())
    or company_id in (select id from company_profiles where user_id = auth.uid())
  );

-- Introductions are readable by match participants
create policy "Users can view their introductions"
  on introductions for select
  using (
    match_id in (
      select m.id from matches m
      where m.talent_id in (select id from talent_profiles where user_id = auth.uid())
         or m.company_id in (select id from company_profiles where user_id = auth.uid())
    )
  );

-- Indexes
create index idx_talent_profiles_user_id on talent_profiles(user_id);
create index idx_company_profiles_user_id on company_profiles(user_id);
create index idx_matches_talent_id on matches(talent_id);
create index idx_matches_company_id on matches(company_id);
create index idx_introductions_match_id on introductions(match_id);
